name: build push dev image

on:
  push:
    branches:
      - 'develop'

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dev
        uses: docker/build-push-action@v2
        id: docker_build_develop
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gsscogs/linked-data-repository:develop
      - name: Develop Image digest
        run: echo ${{ steps.docker_build_develop.outputs.digest }}


--
